[ global ]
    output_path = "../../Outputs/hansard"

###choose one: XML or XML_DIR
[[ XML ]]
    filename = "xmls/1940/1940_05_01.xml"


#[[ XML_DIR ]]
#    path = "xmls"

[ general_options ]
    csv_exist = false
    edit = ["re","flatten"]
    year = [1940,1940]
    overwrite = true
