[ global ]
    output_path = "../../Outputs/hansard"

#[[ XML ]]
#    filename = "xmls/2008/2008-12-01.xml"


[[ XML_DIR ]]
    path = "xmls"

[ general_options ]
    csv_exist = false
    edit = true
    year = [2011,2011]
