[ global ]
    output_path = "../../Outputs/hansard"

#[[ XML ]]
#    filename = "xmls/1926/1926_08_05.xml"


[[ XML_DIR ]]
    path = "xmls"

[ general_options ]
    csv_exist = false
    edit = true
    year = [1901,2024]
