[ global ]
    output_path = "../../Outputs/hansard"

#[[ XML ]]
#    filename = "xmls/1983/1983_04_21.xml"


[[ XML_DIR ]]
    path = "xmls"
#
[ general_options ]
    csv_exist = false
    edit = true
    year = [1970,1998]
    overwrite = true
