[ global ]
    output_path = "../../Outputs/hansard"

#[[ XML ]]
#    filename = "xmls/1983/1983_06_01.xml"


[[ XML_DIR ]]
    path = "xmls"
#
[ general_options ]
    csv_exist = false
    edit = true
    year = [1981,1981]
    overwrite = true
