[ global ]
    output_path = "../../HouseCSV/hansard"

###choose one: XML or XML_DIR
#[[ XML ]]
#    filename = "xmls/1901/1901_05_29.xml"


[[ XML_DIR ]]
    path = "xmls"

[ general_options ]
    csv_exist = false
    edit = ["re","free_node","flatten","flatten"]
    year = [2025,2025]
    overwrite = true
