[ global ]
    output_path = "../../Outputs/hansard"

###choose one: XML or XML_DIR
#[[ XML ]]
#    filename = "xmls/1994/1994_02_09.xml"


[[ XML_DIR ]]
    path = "xmls"

[ general_options ]
    csv_exist = false
    edit = ["re","flatten"]
    year = [1964,1964]
    overwrite = true
