[ global ]
    output_path = "../../HouseCSV/hansard"

###choose one: XML or XML_DIR
#[[ XML ]]
#    filename = "xmls/2009/2009_06_03.xml"


[[ XML_DIR ]]
    path = "house_xmls"

[ general_options ]
    which_house = "house"
    csv_exist = true
    edit = ["re","free_node","flatten","flatten","column_decorate"]
    year = [1901,2025]
    overwrite = true
    sample = true
