[ global ]
    output_path = "../../HouseCSV/hansard"

###choose one: XML or XML_DIR
#[[ XML ]]
#    filename = "xmls/2009/2009_06_03.xml"


[[ XML_DIR ]]
    path = "house_xmls"

[ general_options ]
    which_house = "house"
    csv_exist = true
    edit = ["speaker_time","re","free_node","flatten","flatten","column_decorate","re"]
    year = [1928,1928]
    overwrite = true
    sample = true
    remove_nums = [1,2,3,4,5,6]
