[ global ]
    output_path = "../../SenateCSV/hansard"

###choose one: XML or XML_DIR
#[[ XML ]]
#    filename = "senate_xmls/1999/1999_06_25.xml"


[[ XML_DIR ]]
    path = "senate_xmls"

[ general_options ]
    which_house = "senate"
    csv_exist = false
    edit = ["speaker_time","re","free_node","flatten","flatten","column_decorate","re"]
    year = [1901,1901]
    overwrite = true
    sample = false
    remove_nums = [1,2,3,4,5,6]
    #whether to clean the xml names
    xml_name_clean = true
