[GENERAL_OPTIONS]
YEAR = [1901, 2025]
WHICH_HOUSE = "senate"
OVERWRITE = false
SAMPLE = false
CSV_EXIST = false
EDIT = ["re", "free_node", "flatten", "flatten", "column_decorate"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/SenateCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/SenateCSV/hansard"

[METADATA]
TIME = "19:11:53"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/senate.toml"
DATE = "2025-07-27"

[[XML_DIR]]
PATH = "senate_xmls"
