[GENERAL_OPTIONS]
REMOVE_NUMS = [0, 1, 2, 3, 4, 5, 6]
XML_NAME_CLEAN = false
YEAR = [1901, 2025]
WHICH_HOUSE = "senate"
XML_PARSING = false
SAMPLE = false
CSV_EDIT = false
EDIT = ["speaker_time", "re", "free_node", "flatten", "flatten", "column_decorate", "re"]
RUN_XML = false

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/SenateCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/SenateCSV/hansard"

[METADATA]
TIME = "14:25:41"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/senate.toml"
DATE = "2025-08-04"

[[XML_DIR]]
PATH = "senate_xmls"
