[GENERAL_OPTIONS]
REMOVE_NUMS = [1, 2, 3, 4, 5, 6]
XML_NAME_CLEAN = true
YEAR = [1901, 2025]
WHICH_HOUSE = "senate"
OVERWRITE = true
SAMPLE = false
CSV_EXIST = false
EDIT = ["speaker_time", "re", "free_node", "flatten", "flatten", "column_decorate", "re"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/SenateCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/SenateCSV/hansard"

[METADATA]
TIME = "18:49:52"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/senate.toml"
DATE = "2025-07-29"

[[XML_DIR]]
PATH = "senate_xmls"
