[[XML]]
FILENAME = "xmls/1928/1928_03_02.xml"

[GENERAL_OPTIONS]
YEAR = [1928, 1928]
OVERWRITE = true
SAMPLE = true
CSV_EXIST = false
EDIT = ["re", "free_node", "flatten", "flatten", "column_decorate"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard"

[METADATA]
TIME = "17:19:20"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/hansard.toml"
DATE = "2025-07-08"
