[GENERAL_OPTIONS]
YEAR = [2024, 2024]
OVERWRITE = true
CSV_EXIST = false
EDIT = ["re", "free_node", "flatten"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard"

[METADATA]
TIME = "12:31:02"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/hansard.toml"
DATE = "2025-06-26"

[[XML_DIR]]
PATH = "xmls"
