[GENERAL_OPTIONS]
REMOVE_NUMS = [1, 2, 3, 4, 5, 6]
YEAR = [1928, 1928]
WHICH_HOUSE = "house"
OVERWRITE = true
SAMPLE = true
CSV_EXIST = true
EDIT = ["speaker_time", "re", "free_node", "flatten", "flatten", "column_decorate", "re"]

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard"

[METADATA]
TIME = "22:52:29"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/house.toml"
DATE = "2025-07-17"

[[XML_DIR]]
PATH = "house_xmls"
