[GENERAL_OPTIONS]
REMOVE_NUMS = [0, 1, 2, 3, 4, 5, 6]
XML_NAME_CLEAN = false
YEAR = [1901, 2025]
WHICH_HOUSE = "house"
XML_PARSING = false
SAMPLE = false
CSV_EDIT = false
EDIT = ["speaker_time", "re", "free_node", "flatten", "flatten", "column_decorate", "re"]
RUN_XML = false

[GLOBAL]
BASE_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/"
INPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard"
LOG_FILE = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard/log.txt"
LOGGING = true
OUTPUT_PATH = "/home/eve/Development/ParlinfoSpeechScraper/HouseCSV/hansard"

[METADATA]
TIME = "14:47:37"
ORIGINAL = "/home/eve/Development/ParlinfoSpeechScraper/Inputs/hansard/house.toml"
DATE = "2025-07-30"

[[XML_DIR]]
PATH = "house_xmls"
